<a href="https://colab.research.google.com/github/shaimaeid/basics_of_numpy/blob/main/array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Numeric python list
a=[1,2,3]
b=[2,4,6]

In [3]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [4]:
a+b

[1, 2, 3, 2, 4, 6]

In [5]:
A=np.array(a)
B=np.array(b)

In [6]:
A*=2
A

array([2, 4, 6])

In [7]:
c=A+np.log(B)
c

array([2.69314718, 5.38629436, 7.79175947])

In [8]:
A*B

array([ 4, 16, 36])

In [9]:
A.dot(B)

56

In [10]:
np.dot(A,B)

56

In [11]:
D=np.arange(1,10).reshape((3,3))
D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
D.sum(axis=0)

array([12, 15, 18])

In [13]:
D.sum(axis=1)

array([ 6, 15, 24])

In [14]:
D.sum()

45

# Array Selecting and Slicing

In [27]:
x=np.arange(16)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [30]:
# Explor accessing array elements
print(x[8])

8


In [34]:
# Explor slicing array elements
print(x[-5:])

[11 12 13 14 15]


In [35]:
print(x[[2,4,6]])

[2 4 6]


In [55]:
y=np.arange(1,13).reshape((3,4))
print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [57]:
# Explor accessing 2D array elements
print(y[1,2:])
z=y[1,2:].copy()
print(z)
y[1,2]=70
print(y)
print(z)


[7 8]
[7 8]
[[ 1  2  3  4]
 [ 5  6 70  8]
 [ 9 10 11 12]]
[7 8]
